services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: clinix-db
    environment:
      POSTGRES_DB: clinix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
