services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: clinix-db
    environment:
      POSTGRES_DB: clinix
      POSTGRES_USER: clinix
      POSTGRES_PASSWORD: clinix123
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
