'use client'

import Link from 'next/link'
import Card from '@/components/ui/Card'
import MetricCard from '@/components/ui/MetricCard'
import Badge from '@/components/ui/Badge'
import AIChip from '@/components/ui/AIChip'
import { useApi } from '@/lib/api/client'

// ─── Types ──────────────────────────────────────────────────────────────────
interface DashboardMetrics {
  metrics: {
    consultasHoje: number
    guiasPendentes: number
    guiasProntas: number
    faturamentoMensal: string
  }
}

interface AgendaItem {
  id: string
  dataHora: string
  tipo: string
  status: string
  riscoNoshow: number | null
  paciente: { id: string; nome: string } | null
  medico: { id: string; nome: string; corAgenda: string | null } | null
  convenio: { id: string; nome: string } | null
}

interface GuiaItem {
  id: string
  numeroGuia: string
  status: string
  valorFaturado: string | null
  auditoriaIa: unknown
  paciente: { id: string; nome: string } | null
  convenio: { id: string; nome: string } | null
}

// ─── Convenio badge color map ──────────────────────────────────────────────
const convBadge = (name: string): 'teal' | 'amber' | 'purple' | 'blue' | 'default' => {
  if (name?.startsWith('Unimed')) return 'amber'
  if (name?.startsWith('Amil')) return 'teal'
  if (name?.startsWith('Bradesco')) return 'purple'
  if (name?.startsWith('SulAm')) return 'blue'
  return 'default'
}

const statusBadge = (status: string): { label: string; color: 'green' | 'amber' | 'red' | 'blue' } => {
  switch (status) {
    case 'pendente_revisao': return { label: 'Alerta IA', color: 'amber' }
    case 'pendente_envio': return { label: 'Validado', color: 'green' }
    case 'glosado': return { label: 'Bloqueado', color: 'red' }
    case 'enviado': return { label: 'Enviado', color: 'blue' }
    default: return { label: status, color: 'amber' }
  }
}

const tipoBadge = (tipo: string): { label: string; color: 'green' | 'blue' } => {
  return tipo === 'primeira_consulta'
    ? { label: '1ª consulta', color: 'green' }
    : { label: 'Retorno', color: 'blue' }
}

// ─── Insights (static — generated by AI agent) ──────────────────────────────
const INSIGHTS = [
  {
    bg: 'rgba(245,158,11,0.08)',
    border: 'rgba(245,158,11,0.18)',
    tag: '⚠ NOVA REGRA APRENDIDA',
    tagColor: '#fbbf24',
    body: 'Unimed código 40301-4 exige laudo PDF.',
    conf: 'Confiança 96%',
    confColor: '#fbbf24',
  },
  {
    bg: 'rgba(16,185,129,0.08)',
    border: 'rgba(16,185,129,0.18)',
    tag: '✓ GLOSA EVITADA',
    tagColor: '#34d399',
    body: 'R$ 890 — agente bloqueou guia Pedro Rocha',
    conf: null,
    confColor: '',
  },
  {
    bg: 'rgba(139,92,246,0.08)',
    border: 'rgba(139,92,246,0.18)',
    tag: '◈ PADRÃO DETECTADO',
    tagColor: '#c4b5fd',
    body: 'Hapvida CID F32 glosado 4×',
    conf: null,
    confColor: '',
  },
]

// ─── Table helpers ──────────────────────────────────────────────────────────
const thStyle: React.CSSProperties = {
  padding: '6px 10px',
  textAlign: 'left',
  fontSize: 10,
  fontWeight: 600,
  letterSpacing: '0.07em',
  textTransform: 'uppercase',
  color: 'var(--text3)',
  whiteSpace: 'nowrap',
  borderBottom: '1px solid var(--border)',
}

const tdStyle: React.CSSProperties = {
  padding: '9px 10px',
  fontSize: 13,
  color: 'var(--text)',
  verticalAlign: 'middle',
  borderBottom: '1px solid var(--border)',
}

// ─── Loading skeleton ──────────────────────────────────────────────────────
function LoadingRow({ cols }: { cols: number }) {
  return (
    <tr>
      {Array.from({ length: cols }).map((_, i) => (
        <td key={i} style={tdStyle}>
          <div style={{ height: 14, width: '70%', background: 'var(--bg3)', borderRadius: 6, animation: 'pulse 1.5s infinite' }} />
        </td>
      ))}
    </tr>
  )
}

// ─── Page ───────────────────────────────────────────────────────────────────
export default function DashboardPage() {
  const { data: dashData } = useApi<DashboardMetrics>('/dashboard')
  const { data: agendaData } = useApi<{ agendamentos: AgendaItem[] }>('/agenda')
  const { data: guiasData } = useApi<{ guias: GuiaItem[] }>('/faturamento/guias')

  const m = dashData?.metrics
  const agenda = agendaData?.agendamentos?.slice(0, 5) ?? []
  const auditGuias = guiasData?.guias?.slice(0, 4) ?? []

  const today = new Date()
  const dateStr = today.toLocaleDateString('pt-BR', { day: 'numeric', month: 'long' })

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

      {/* ── Metric cards row ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 }}>
        <MetricCard
          label="Atendimentos hoje"
          value={m?.consultasHoje ?? '—'}
          delta={m ? `${m.consultasHoje} agendados` : 'carregando...'}
          deltaDirection="up"
        />
        <MetricCard
          label="Faturado no mês"
          value={m?.faturamentoMensal ?? '—'}
          delta={m ? 'este mês' : 'carregando...'}
          deltaDirection="up"
        />
        <MetricCard
          label="Guias pendentes"
          value={m?.guiasPendentes ?? '—'}
          delta="aguardando revisão"
          deltaDirection="neutral"
          style={{ borderLeft: '3px solid #fbbf24' }}
        />
        <MetricCard
          label="Prontas para envio"
          value={m?.guiasProntas ?? '—'}
          delta="pré-auditadas pela IA"
          deltaDirection="up"
        />
      </div>

      {/* ── Two-column grid ── */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>

        {/* Left – Agenda */}
        <Card style={{ padding: 0, overflow: 'hidden' }}>
          <div
            style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              padding: '14px 16px 12px', borderBottom: '1px solid var(--border)',
            }}
          >
            <div>
              <div style={{ fontWeight: 600, fontSize: 14, color: 'var(--text)' }}>
                Agenda — hoje
              </div>
              <div style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'var(--mono)', marginTop: 2 }}>
                {dateStr} · {m?.consultasHoje ?? '—'} agendamentos
              </div>
            </div>
            <Link
              href="/agenda"
              style={{
                fontSize: 12, color: 'var(--accent)', textDecoration: 'none', fontWeight: 500,
                whiteSpace: 'nowrap', padding: '4px 10px', borderRadius: 6,
                border: '1px solid rgba(59,130,246,0.25)', background: 'rgba(59,130,246,0.08)',
              }}
            >
              Ver agenda →
            </Link>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr>
                  <th style={thStyle}>Hora</th>
                  <th style={thStyle}>Paciente</th>
                  <th style={thStyle}>Médico</th>
                  <th style={thStyle}>Convênio</th>
                  <th style={thStyle}>Status</th>
                </tr>
              </thead>
              <tbody>
                {!agendaData && [1, 2, 3].map((i) => <LoadingRow key={i} cols={5} />)}
                {agenda.map((row) => {
                  const hora = new Date(row.dataHora).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })
                  const tb = tipoBadge(row.tipo)
                  return (
                    <tr key={row.id} style={{ transition: 'background 0.12s' }}
                      onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.025)' }}
                      onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent' }}
                    >
                      <td style={tdStyle}>
                        <span style={{ fontFamily: 'var(--mono)', fontSize: 12, background: 'var(--bg3)', padding: '2px 7px', borderRadius: 5, color: 'var(--text2)' }}>
                          {hora}
                        </span>
                      </td>
                      <td style={tdStyle}>
                        <span style={{ fontSize: 13, color: 'var(--text)' }}>
                          {row.paciente?.nome ?? '—'}
                        </span>
                        {(row.riscoNoshow ?? 0) > 0.5 && (
                          <span style={{ marginLeft: 5, fontSize: 12, color: '#fbbf24' }} title="Risco de no-show">⚠</span>
                        )}
                      </td>
                      <td style={tdStyle}>
                        <span style={{ display: 'flex', alignItems: 'center', gap: 5 }}>
                          <span style={{ color: row.medico?.corAgenda ?? '#3b82f6', fontSize: 10 }}>●</span>
                          <span style={{ fontSize: 12, color: 'var(--text2)' }}>{row.medico?.nome ?? '—'}</span>
                        </span>
                      </td>
                      <td style={tdStyle}>
                        <Badge color={convBadge(row.convenio?.nome ?? '')}>{row.convenio?.nome ?? 'Particular'}</Badge>
                      </td>
                      <td style={tdStyle}>
                        <Badge color={tb.color}>{tb.label}</Badge>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </Card>

        {/* Right – Guias em auditoria */}
        <Card style={{ padding: 0, overflow: 'hidden' }}>
          <div
            style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              padding: '14px 16px 12px', borderBottom: '1px solid var(--border)',
            }}
          >
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontWeight: 600, fontSize: 14, color: 'var(--text)' }}>
                Guias em auditoria
                <AIChip size="sm" />
              </div>
              <div style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'var(--mono)', marginTop: 2 }}>
                {m?.guiasPendentes ?? '—'} pendentes de revisão
              </div>
            </div>
            <Link
              href="/faturamento"
              style={{
                fontSize: 12, color: 'var(--accent)', textDecoration: 'none', fontWeight: 500,
                whiteSpace: 'nowrap', padding: '4px 10px', borderRadius: 6,
                border: '1px solid rgba(59,130,246,0.25)', background: 'rgba(59,130,246,0.08)',
              }}
            >
              Ver todas →
            </Link>
          </div>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr>
                  <th style={thStyle}>Paciente</th>
                  <th style={{ ...thStyle, textAlign: 'right' }}>Valor</th>
                  <th style={thStyle}>Status IA</th>
                  <th style={{ ...thStyle, width: 40 }} />
                </tr>
              </thead>
              <tbody>
                {!guiasData && [1, 2, 3].map((i) => <LoadingRow key={i} cols={4} />)}
                {auditGuias.map((guia) => {
                  const sb = statusBadge(guia.status)
                  const valor = guia.valorFaturado ? `R$ ${parseFloat(guia.valorFaturado).toLocaleString('pt-BR')}` : '—'
                  return (
                    <tr key={guia.id}
                      style={{ transition: 'background 0.12s', cursor: 'pointer' }}
                      onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.025)' }}
                      onMouseLeave={(e) => { e.currentTarget.style.background = 'transparent' }}
                    >
                      <td style={tdStyle}>
                        <div style={{ fontSize: 13, color: 'var(--text)', fontWeight: 500 }}>
                          {guia.paciente?.nome ?? '—'}
                        </div>
                      </td>
                      <td style={{ ...tdStyle, textAlign: 'right' }}>
                        <span style={{ fontFamily: 'var(--mono)', fontSize: 12, color: 'var(--text2)' }}>
                          {valor}
                        </span>
                      </td>
                      <td style={tdStyle}>
                        <Badge color={sb.color}>{sb.label}</Badge>
                      </td>
                      <td style={{ ...tdStyle, textAlign: 'right' }}>
                        <span style={{ fontSize: 12, color: 'var(--text3)', fontWeight: 600 }}>
                          {guia.convenio?.nome ?? ''} →
                        </span>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </Card>
      </div>

      {/* ── Insights card ── */}
      <Card style={{ padding: 0, overflow: 'hidden' }}>
        <div
          style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '14px 16px 12px', borderBottom: '1px solid var(--border)',
          }}
        >
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontWeight: 600, fontSize: 14, color: 'var(--text)' }}>
              Insights do agente
              <AIChip size="sm" />
            </div>
            <div style={{ fontSize: 11, color: 'var(--text3)', fontFamily: 'var(--mono)', marginTop: 2 }}>
              Padrões detectados nas últimas 24h
            </div>
          </div>
          <Link
            href="/agente"
            style={{
              fontSize: 12, color: 'var(--accent)', textDecoration: 'none', fontWeight: 500,
              whiteSpace: 'nowrap', padding: '4px 10px', borderRadius: 6,
              border: '1px solid rgba(59,130,246,0.25)', background: 'rgba(59,130,246,0.08)',
            }}
          >
            Agente completo →
          </Link>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 0 }}>
          {INSIGHTS.map((ins, i) => (
            <div
              key={i}
              style={{
                padding: '16px 18px', background: ins.bg,
                borderRight: i < INSIGHTS.length - 1 ? '1px solid var(--border)' : 'none',
              }}
            >
              <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.07em', color: ins.tagColor, fontFamily: 'var(--mono)', marginBottom: 8, display: 'flex', alignItems: 'center', gap: 5 }}>
                <span style={{ display: 'inline-block', width: 6, height: 6, borderRadius: '50%', background: ins.tagColor, flexShrink: 0 }} />
                {ins.tag}
              </div>
              <div style={{ fontSize: 13, color: 'var(--text)', lineHeight: 1.5, marginBottom: ins.conf ? 8 : 0 }}>
                {ins.body}
              </div>
              {ins.conf && (
                <div style={{ fontSize: 11, color: ins.confColor, fontFamily: 'var(--mono)', fontWeight: 500 }}>
                  {ins.conf}
                </div>
              )}
            </div>
          ))}
        </div>
      </Card>
    </div>
  )
}
